# Generated by Django 3.0.7 on 2020-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=256)),
                ('p_age', models.PositiveIntegerField()),
                ('p_gender', models.CharField(max_length=200)),
                ('p_berth', models.CharField(max_length=256)),
            ],
        ),
    ]
