# Generated by Django 3.0.7 on 2020-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train_app', '0004_passengermodel_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='Ticket_id',
            field=models.IntegerField(null=True),
        ),
    ]
