# Generated by Django 3.0.7 on 2020-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train_app', '0006_auto_20200911_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='Payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
